CREATE TABLE RECORD (
    IDT_RECORD BIGSERIAL NOT NULL PRIMARY KEY,
    NAM_TOPIC VARCHAR(255),
    NUM_PARTITION NUMERIC(20, 0),
    TXT_KEY TEXT,
    TXT_RECORD_VALUE TEXT,
    JSN_HEADERS TEXT,
    DAT_CREATED TIMESTAMP DEFAULT NOW()
);

CREATE INDEX RECORD_IDX1 ON RECORD(DAT_CREATED);
CREATE INDEX RECORD_IDX2 ON RECORD(TXT_KEY);

CREATE TABLE PARAMETER(
    IDT_PARAMETER VARCHAR(255) NOT NULL PRIMARY KEY,
    VAL_PARAMETER TEXT,
    DAT_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    DAT_UPDATED TIMESTAMP
);
