CREATE TABLE TTO_RECORD (
    IDT_TTO_RECORD VARCHAR(36) NOT NULL PRIMARY KEY,
    NAM_TOPIC VARCHAR(255),
    NUM_PARTITION NUMERIC(20, 0),
    TXT_KEY TEXT,
    TXT_RECORD_VALUE TEXT,
    JSN_HEADERS TEXT,
    DAT_CREATED TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', NOW())
);

CREATE INDEX TTO_RECORD_IDX1 ON RECORD(DAT_CREATED);
CREATE INDEX TTO_RECORD_IDX2 ON RECORD(TXT_KEY);

CREATE TABLE PARAMETER(
    IDT_PARAMETER VARCHAR(255) NOT NULL PRIMARY KEY,
    VAL_PARAMETER TEXT,
    DAT_CREATED TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', NOW()),
    DAT_UPDATED TIMESTAMP
);
