ALTER TABLE TTO_RECORD_PROCESSED ADD NAM_TOPIC VARCHAR(255);
ALTER TABLE TTO_RECORD_PROCESSED ADD NUM_PARTITION NUMERIC(20, 0);
ALTER TABLE TTO_RECORD_PROCESSED ADD TXT_KEY LONGVARCHAR;
ALTER TABLE TTO_RECORD_PROCESSED ADD TXT_VALUE LONGVARCHAR;
ALTER TABLE TTO_RECORD_PROCESSED ADD TXT_HEADERS LONGVARCHAR;
